In [7]:
import pandas as pd

# загрузка данных
file_path = './data/data_raw_english_columns.csv'
df = pd.read_csv(file_path, low_memory=False)

# вывод 5 первых строк
df.head(5)

,year,program_group,university,avg_ege_paid,ege_change_prev_year,enrolled_paid,cost_of_education_rub,avg_ege_budget,enrolled_budget,ege_excludes_individual,...,inflation_rate_percent,mrot_rub,avg_salary_rub,real_salary_growth_percent,cpi_index,base_cpi,base_inflation_percent,gdp_deflator,population_million,unemployment_rate_percent
0,2024,Психология,"Адыгейский гос. ун-т., г. Майкоп",57.2,-10.8,3,113.4,68.7,22.0,Да,...,7.4,19.2,75.0,8.5,251.3,100.6,7.15,129.4,146.2,2.9
1,2024,Лингвистика и иностранные языки,"Адыгейский гос. ун-т., г. Майкоп",61.3,5.7,17,113.4,76.6,25.0,Да,...,7.4,19.2,75.0,8.5,251.3,100.6,7.15,129.4,146.2,2.9
2,2024,Юриспруденция,"Адыгейский гос. ун-т., г. Майкоп",55.7,-7.4,30,113.4,82.3,10.0,Да,...,7.4,19.2,75.0,8.5,251.3,100.6,7.15,129.4,146.2,2.9
3,2024,Физическая культура,"Адыгейский гос. ун-т., г. Майкоп",45.9,-2.4,2,158.3,63.3,50.0,Да,...,7.4,19.2,75.0,8.5,251.3,100.6,7.15,129.4,146.2,2.9
4,2024,Реклама и связи с общественностью,"Адыгейский гос. ун-т., г. Майкоп",52.0,4.7,2,113.4,70.2,12.0,Да,...,7.4,19.2,75.0,8.5,251.3,100.6,7.15,129.4,146.2,2.9